version: 0.2
phases:
  install:
    commands:
      - apt-get update
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build --prod

artifacts:
  files:
    - '**/*'
  base-directory: 'dist*'
 discard-paths: yes
