version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo installing dependencies...
      - npm i -g @angular/cli
      - npm install
  build:
    commands:
      - npm run build --prod

artifacts:
  files:
    - '**/*'
  base-directory: 'dist*'
  discard-paths: yes
