version: 0.2
phases:
  install:
    commands:
      - apt-get update
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - ng build
  post_build:
    commands:
      - aws s3 sync dist/Study-Force-FrontEnd/ s3://2102-study-force-frontend-dev --acl 'public-read' --delete
